version: '3'

services: 
  vue:
    build:
      context: . 
      dockerfile: Dockerfile
    image: node:lts
    container_name: web_app
    restart: unless-stopped
    entrypoint: npm run 
    command: serve
    environment: 
      ENVIRONMENT: "development"
    ports: 
      - "8080:8080"
    networks: 
      - vue_network

networks: 
  vue_network:
    driver: bridge