# This is a basic workflow to help you get started with Actions

name: CICD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install Dependencies
        run: |
          npm install @vue/cli
          vue upgrade --next
          npm install 

      - name: Build App
        run: npm run build
  
  test:
    runs-on: ubuntu-latest
    if: success()
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Run tests
        run: |
          npm run lint
          npm run test:unit
          npm run test:e2e
  deploy:
    runs-on: ubuntu-latest
    if: success() && github.event_name == ${{ 'push' }}
    needs: [build, test]
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/cache
            !~/cache/exclude
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Go to compiled path
        run: cd dist
      - name: Push and deploy
        run: |
          git init
          git add --all
          git commit -m"Deploy on $(date +%c)"
          git push -f https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git master:page
